### ISSUE TITLE
Changes made to 'decay'

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/maps#11]
In short; the map has been made slightly smaller by removing the tall pipe room and some of the connecting areas. The underground passage has been shortened in length and now better connects to the rest of the map. Some areas have had the texturing improved and weapon placement adjusted.

I've playtested it's current state with 6 bots and it seems to flow better, there's more action across the map. Here's the forum link with the updated map file so that anyone can test it, if they cannot find any more issues with the map. I've named it decay2 so that you can easily compare the changes. 
http://redeclipse.net/forum/viewtopic.php?f=5&t=728#p7567

**Comment by qreeves** [comment]
This one I'd say can go straight to a pull request and be merged immediately.
