### ISSUE TITLE
Decay map/cfg not upto date

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/maps#20]
This commit cd01ca8c44c59a275c3a6394787fd6aa149d2d06 reintroduced an old version of decay; cfg/mpz files should be more recent versions. 

The most recent files are attached here:
http://redeclipse.net/forum/viewtopic.php?f=5&t=728&p=7567&hilit=decay#p7567

**Comment by qreeves** [comment]
[decay2.zip](https://github.com/red-eclipse/maps/files/382907/decay2.zip)
