### ISSUE TITLE
Picking Maps for Removal

### ISSUE THREAD

**Issue by acerspyro** [redeclipse/maps#29]

**Comment by TheAssassin** [comment]
I don't think it is a good idea to reduce the amount of maps that are "shipped" with the game, as this is unlike to be the solution of the problem you mentioned. This is due to the fact that many server owners tend to add new or alternative maps to their server, and thus could add the removed maps again, which again leads to a cluttered menu, but then the clients have to download the map everytime they want or have to play one of those. Edit: I see you mentioned that, too, but I still think this actually makes your approach problematic.

In my opinion, a more useful approach is to modify the list in the default server configuration to be shorter.

**Comment by acerspyro** [comment]
The biggest issue I have with the amount of maps present in the game is the
clutter in the map selection menu. There are so many maps that no one ever
plays anymore.

**Comment by TheAssassin** [comment]
Such as? I expected a few suggestions reading the title of this issue...

**Comment by acerspyro** [comment]
Such as Oneiroi, but anything I choose would be very biased, as it represents my sole opinion and not the average opinion of the playerbase.

**Comment by TheAssassin** [comment]
Well, without a few suggestions, this issue won't make any progress.
We should set up a poll about that in the forums.

**Comment by acerspyro** [comment]
Good idea. Should we also put the poll into the IRC topic so that it grabs people's attention, and as such, we get as much of the player base as possible? Or even make the poll outside of the forums, allowing people without accounts to vote (useful for asking people in-game to vote), as adding or removing key maps could potentially cost us a player base.

**Comment by ghost** [comment]
Construct the poll as maps players would like to see in the main game, and give them the option to vote for lots (or all) of the maps.
This'll give us a list of maps which the most people are happy with, rather than the most favourite/hated map.

Alternatively, pull stats from the stat system to work out which maps aren't being played (note: results may be biased against larger maps and duel/survivor maps).

**Comment by TheAssassin** [comment]
I'm preparing exactly such a thing, @JeffBobbo, using some external tool.

**Comment by acerspyro** [comment]
@TheAssassin If you're going to make your own in-house tool, could you show a mapshot alongside the name of the map, so players don't have to go in the game and check "Oh wait what map is that again? Oh yeah."

**Comment by TheAssassin** [comment]
Yeah, that sounds like a good idea. IIRC we already have such screenshots in the maps repository, so that's no problem at all.

**Comment by shirepirate** [comment]
it's better to decide this sort of thing near a major release. also it doesn't have to be an arbitrary decision anymore as we have stats to back it up.

taking a quick glance it seems that pumpstation, biolytic, vorticity, cutec, tower, oneiroi & enyo are quite unpopular compared to other maps.

when the time comes it might be better to narrow it down to these few and ask the community, then have someone make an executive decision on which will get the chopping block.

**Comment by acerspyro** [comment]
@shirepirate does major release mean 1.5.9 or 1.6?

**Comment by shirepirate** [comment]
i meant 1.6, but that's up to @qreeves of course.

**Comment by no-lex** [comment]
If it helps, the ten least popular DM maps (from least popular to most popular) are _decay_ (58 plays), _pumpstation_ (74), _biolytic_ (76) , _vorticity_ (78), _erosion_ (87), _octavus_ (91) , _tribal_ (100), _tower_ (101), _nova_ (101),_ and,_suspended_ (103).

**Comment by TheAssassin** [comment]
First of all, I have to say I'm sorry that I forgot I wanted to create a poll about that for our players. But now, I think that might not necessarily have been the right way anyway. The stats way appears to be better.

Your statement does unfortunately have very few statistical value, as it represents only a very small piece of the game (deathmatch mode is not everything that is played, and some of the maps are not suited for this gamemode (e.g. suspended is a CTF classic)).

Picking up your idea, I'd suggest a statistical analysis using the popularity of maps (represented by the number of games with these maps). Every single game needs to be weighted, though, to represent the different gamemodes. We should define a list of basic games (i.e., gladiator deathmatch has a very different behavior compared to normal deathmatch, same goes for hold bomber-ball and normal bomber-ball (attack is pretty much the same as normal bb, so I'd say we can group them). We can group e.g. insta deathmatch, deathmatch, hard deathmatch etc., or any kind of survivor deathmatch (except for gladiator mode), and so on. Then, we calculate the popularity of these gamemodes from the list of games. This weight is added to the map's popularity value. Another approach is to create separate graphs for each gamemode. I think it's worth to work on both approaches. I'm curious about the results. This way, we get a better inspection of how popular a map is, and respect several circumstances, like the actual gamemode, which is of course important as e.g. torus for gladiator needs to be regarded differently than darkness for CTF.

I hope I could describe my idea well enough. Anyway, I'll add that to my list for Thursday.
@qreeves / @shacknetisp, I'd need the raw stats for this. Ideally, you send me a copy of the database, so I can create the according queries in SQL. You should have my mail address. Please send it encryptedly, it contains potentially private data.

The analysis wouldn't be perfect either, as the statistics represent only some of the servers, but well enough for our purposes. Ideas how to adjust the values correctly are welcome. For instance, server chosen games should not be considered, also, when people left instantly (e.g. within the first 30 seconds), a game is not representative.

It shouldn't be very hard to create these graphs. I plot a lot at work, and have gained quite some experience with this kind of descriptive statistics.

**Comment by no-lex** [comment]
The statistics consider all games played for each listed map: I filtered to DM maps only because race/gladiator maps should be considered separately (I believe CTF maps are a strict subset of DM maps). I don't think unfinished games get counted under statistics (Games list doesn't list any short non-race games). 
    An important trend to note is the declining popularity of maps that are lower on the list as can be seen in this lovely scatterplot without axis labels: (y axis is plays; x axis is position in list)
![image](https://cloud.githubusercontent.com/assets/23445929/26380297/94227b14-3fd2-11e7-8a9b-12635ccc5c02.png)

**Comment by no-lex** [comment]
Maps I personally want removed:
stone deadsimple deathtrap decay dutility tower spacetech processing keystone2k erosion futuresport vorticity ares affluence canyon longestyard dutility 

Maps I personally want in the game:
ubik panic* pumpstation* deli ghost depot* nova octavus plantation* polaris abuse*

*With a remix

**Comment by shacknetisp** [comment]
With https://github.com/red-eclipse/maps/commit/5227942392b8a1f0bae2cc896e98c2e51fbc184c many maps have been removed. See https://redeclipse.net/wiki/Upcoming_Changes#Maps for more plans and details, discussion is no longer occurring here on this issue.

**Comment by cloudziq** [comment]
omg...  I-guy want maps to removal.. maybe first fix that issue with server-downloaded-maps going to /maps folder ?  This is real problem, this cause file clutter and not a few official maps (I have over 4000 files that I dont want here).

**Comment by qreeves** [comment]
https://github.com/red-eclipse/base/issues/531

**Comment by IceflowRE** [comment]
Just a hint, i already reacted and made them available again on my servers.

**Comment by no-lex** [comment]
Why? They're not ported and look terrible, often with massive lighting glitches. Nobody's going to play DM on totally broken maps.

**Comment by IceflowRE** [comment]
Well "look terrible" your opinion. "Massive lighting glitches" i dont discovered some so fare, but on a sauerbraten map i did. "totally borken" thats not true. Ok, some maps looks with tesseract ~not correctly~ weird illuminated, but thats all.
I think you never played sauerbraten maps in RE? I loved some of them like asgard, xeon, venice. Bringing them back too the tesseract engine would be cool.

**Comment by acerspyro** [comment]
They would still have to be ported. We can't have "passable" maps floating around. Brand image is something everyone seems to forget.
