### ISSUE TITLE
Generate descriptions for each map

### ISSUE THREAD

**Issue by qreeves** [redeclipse/maps#37]
The next release has support for "map descriptions", which are shown when hovering over a map with the mouse. All maps should be updated to include a short blurb in this field.

**Comment by no-lex** [comment]
It would be helpful to clear up the format and size of the descriptions. Will it be in its own seperate file or part of the map's .txt or .cfg? What length will it be and how should it be formatted? What information should it contain- a subjective description of its important characteristics (looks, feel) or an objective description of its features (gamemodes, d&c points, numbers of weapons, etc.)?

**Comment by qreeves** [comment]
It is a variable, `mapdesc` - but those are very good questions. I think a subjective description works best, perhaps with some story element if the map has a particular theme behind it.

**Comment by IceflowRE** [comment]
The Wiki will help for finding descriptions. Iam myself have no time to do it now :/

**Comment by no-lex** [comment]
About how long would a description be? The wiki descriptions are complete but a bit long-winded at times.

**Comment by qreeves** [comment]
I'd suggest they remain rather short, they're being used in the tooltips:

![20170701140554](https://user-images.githubusercontent.com/3297929/27758989-7f81d896-5e66-11e7-83ce-b8cc25c880f0.png)

**Comment by no-lex** [comment]
I commited a mapdesc into #38's config file. Is it formatted correctly, and is it too long or too short?

**Comment by freezurbern** [comment]
Another place for mapdesc could be the loading screen

**Comment by Jigoku** [comment]
Closing, as maps now have descriptions.
